openapi: 3.2.0
info:
  version: ${project.version}
  title: Metrics Reporter Reports API
  x-logo:
    url: images/logo
servers:
- url: ''
tags:
- name: Reports
paths:
  /reports/{catalogueId}/{languageCode}:
    get:
      summary: Returns the report in the specified format
      operationId: getCatalogueReport
      parameters:
      - name: catalogueId
        in: path
        description: Catalogue id
        required: true
        schema:
          type: string
      - name: languageCode
        in: path
        description: Language code of the report to be retrieved
        required: true
        schema:
          type: string
          enum:
          - bg
          - cs
          - da
          - de
          - el
          - en
          - es
          - et
          - fi
          - fr
          - ga
          - hr
          - hu
          - it
          - lt
          - lv
          - mt
          - nl
          - false
          - pl
          - pt
          - ro
          - sk
          - sl
          - sv
      responses:
        '200':
          description: Binary file
          content:
            application/pdf:
              schema:
                type: string
                format: binary
            application/vnd.oasis.opendocument.spreadsheet:
              schema:
                type: string
                format: binary
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid request.
      tags:
      - Reports
