openapi: 3.2.0
info:
  version: 4.3.3
  title: piveau hub-repo service Actions API
  description: The API simplifies the management of DCAT resources, adhering to the DCAT-AP standard for structured data descriptions.
  x-logo:
    url: images/logo
tags:
- name: Actions
  x-displayName: Action API
  description: 'The action API utilizes the JSON-RPC 2.0 specification with the following constraints:


    * `id` reference needs to be a string

    * `params` are passed as object map, not as array list

    * `data` of an error is an object

    * Batch processing of actions is not yet supported


    Although a correlation identifier (`id`) is not necessary on top of HTTP, you should always include it to allow

    the server to distinguish between sync calls and notifications.'
paths:
  /action:
    post:
      tags:
      - Actions
      description: Post a JSON-RPC request to make a call to an action
      summary: Call an Action
      operationId: postAction
      requestBody:
        description: The action in JSON-RPC format
        required: true
        content:
          application/json:
            schema:
              type: object
      security:
      - ApiKeyAuth: []
      - BearerAuth: []
      responses:
        '200':
          description: JSON-RPC Response
          content:
            application/json:
              schema:
                type: object
        '202':
          description: In case of an omitted `id` correlator
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
