openapi: 3.2.0
info:
  version: 5.3.11
  title: hub-search Data Services API
  description: Hub-Search is a powerful search solution designed to function as a Metadata Search Service for the Open Data Portal.
  x-logo:
    url: images/logo
servers:
- url: ''
tags:
- name: Data Services
paths:
  /dataservices/{id}:
    get:
      description: Get a single DataService based on the ID
      summary: Get a single Data Service
      operationId: getDataService
      tags:
      - Data Services
      parameters:
      - name: id
        in: path
        description: Id of the requested Data Service
        required: true
        schema:
          type: string
      responses:
        '200':
          $ref: '#/components/responses/DataServiceSuccess'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      summary: Create or Update a Data Service
      operationId: putDataService
      tags:
      - Data Services
      security:
      - ApiKeyAuth: []
      parameters:
      - name: id
        in: path
        description: ID of the new or existing Data Service
        required: true
        schema:
          type: string
      - name: catalogueId
        in: query
        description: ID of the catalogue to which the dataservice belongs
        required: true
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/RDFBody'
      responses:
        '201':
          description: Data Service created or updated successfully
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      description: Endpoint to delete a given Data Service
      summary: Delete a Data Service
      operationId: deleteDataService
      tags:
      - Data Services
      security:
      - ApiKeyAuth: []
      parameters:
      - name: id
        in: path
        description: Id of the data service
        required: true
        schema:
          type: string
      responses:
        '200':
          $ref: '#/components/responses/DatasetSuccessId'
        '202':
          description: Accepted
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  responses:
    BadRequest:
      description: Validation error / Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: false
              message:
                type: string
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: false
              message:
                type: string
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: false
              message:
                type: string
    DataServiceSuccess:
      description: DataService response object
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: true
              result:
                $ref: '#/components/schemas/DataService'
    DatasetSuccessId:
      description: Dataset response ID
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: true
              result:
                type: object
                properties:
                  id:
                    type: string
  schemas:
    DataService:
      description: Base model for a data service
      type: object
      properties:
        page:
          type: array
          items:
            type: object
            properties:
              title:
                type: object
                additionalProperties:
                  type: string
              description:
                type: object
                additionalProperties:
                  type: string
              format:
                type: object
                properties:
                  format_types:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        label:
                          type: object
                          additionalProperties:
                            type: string
                  id:
                    type: string
                  label:
                    type: string
                  resource:
                    type: string
              resource:
                type: string
        contact_point:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              name:
                type: string
              email:
                type: string
              address:
                type: string
              telephone:
                type: string
              url:
                type: array
                items:
                  type: string
              organisation_name:
                type: string
              resource:
                type: string
        description:
          type: object
          additionalProperties:
            type: string
        keywords:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              label:
                type: string
              language:
                type: string
        topic_category:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              label:
                type: object
                additionalProperties:
                  type: string
              resource:
                type: string
        publisher:
          type: object
          properties:
            type:
              type: string
            name:
              type: string
            email:
              type: string
            homepage:
              type: string
            resource:
              type: string
        endpoint_description:
          type: array
          items:
            type: string
        catalog:
          type: object
          properties:
            source_type:
              type: string
            is_part_of:
              type: string
            id:
              type: string
          required:
          - id
        license:
          type: object
          properties:
            id:
              type: string
            label:
              type: string
            description:
              type: string
            la_url:
              type: string
            resource:
              type: string
        serves_dataset:
          type: array
          items:
            type: string
        theme:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              label:
                type: object
                additionalProperties:
                  type: string
              resource:
                type: string
        hvd_category:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              label:
                type: object
                additionalProperties:
                  type: string
              resource:
                type: string
        title:
          type: object
          additionalProperties:
            type: string
        conforms_to:
          type: array
          items:
            type: object
            properties:
              resource:
                type: string
              label:
                type: string
        translation_meta:
          type: object
          properties:
            full_available_languages:
              type: array
              items:
                type: string
            details:
              type: object
              additionalProperties:
                type: object
                properties:
                  machine_translated:
                    type: boolean
                  original_language:
                    type: string
                  issued:
                    type: string
                  received:
                    type: string
            status:
              type: string
        reference_system:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              resource:
                type: string
              label:
                type: string
        applicable_legislation:
          type: array
          items:
            type: string
        format:
          type: object
          properties:
            id:
              type: string
            label:
              type: string
            resource:
              type: string
            format_types:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  label:
                    type: object
                    additionalProperties:
                      type: string
        id:
          type: string
        landing_page:
          type: array
          items:
            type: object
            properties:
              title:
                type: object
                additionalProperties:
                  type: string
              description:
                type: object
                additionalProperties:
                  type: string
              format:
                type: object
                properties:
                  format_types:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        label:
                          type: object
                          additionalProperties:
                            type: string
                  id:
                    type: string
                  label:
                    type: string
                  resource:
                    type: string
              resource:
                type: string
        access_right:
          type: object
          properties:
            resource:
              type: string
            label:
              type: string
        endpoint_url:
          type: array
          items:
            type: string
  requestBodies:
    RDFBody:
      required: true
      content:
        application/ld+json:
          schema:
            type: object
        application/n-triples:
          schema:
            type: string
        application/n-quads:
          schema:
            type: string
        application/trig:
          schema:
            type: string
        application/trix:
          schema:
            type: string
        text/turtle:
          schema:
            type: string
        text/n3:
          schema:
            type: string
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
x-tagGroups:
- name: Resources
  tags:
  - Resources
  - EditorialContent
- name: Searching
  tags:
  - Search
  - Feeds
- name: DCAT-AP
  tags:
  - Datasets
  - Data Services
  - Dataset Series
  - Catalogues
  - Vocabularies
- name: Misc
  tags:
  - Gazetteer
  - Ckan
  - Organizations
